name: Step 1 # Create a branch

# Triggers when the user creates a new branch 'my-first-branch'.

on:
  push:
    branches:
      - "my-first-branch"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_2_FILE: ".github/steps/2-commit-a-file.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.5.0

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise]
    uses: skills/exercise-toolkit/.github/workflows/post-step-content.yml@post-next-step-content
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}
      step-content-file: ${{ env.STEP_2_FILE }}
      enable-workflows: Step 2
