name: Step 4 # Merge your pull request

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  actions: write
  issues: write

env:
  REVIEW_FILE: ".github/steps/x-review.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.5.0

  post_review_content:
    name: Post review content
    needs: [find_exercise]
    if: |
      !github.event.repository.is_template
    uses: skills/exercise-toolkit/.github/workflows/post-step-content.yml@post-next-step-content
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}
      step-content-file: ${{ env.REVIEW_FILE }}

  finish_exercise:
    name: Finish Exercise
    needs: [find_exercise, post_review_content]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.5.0
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}

